name: bluejean-prod
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        image: bluejean-backend-prod
        container_name: bluejean-app-prod
        restart: unless-stopped
        tty: true
        ports:
            - "8004:8000"
        env_file:
            - .env.prod
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - bluejean-network-prod

    db:
        image: mysql:8.0
        container_name: bluejean-mysql-prod
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        env_file:
            - .env.prod
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-backend}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata-prod:/var/lib/mysql/
        networks:
            - bluejean-network-prod

networks:
    bluejean-network-prod:
        driver: bridge

volumes:
    dbdata-prod:
        driver: local
